### ISSUE TITLE
import.meta causes 'Module parse failed: Unexpected token ' at yarn start

### ISSUE THREAD

**Issue by halmos** [electron-react-boilerplate/electron-react-boilerplate#2709]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Running `yarn start` should succeed without error. 

## Current Behavior

The following error is thrown:
```
Module parse failed: Unexpected token (20:19)
File was processed with these loaders:
* ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
...
>   var test = import.meta.url;
```
for ts/js files containing `import.meta`

## Steps to Reproduce

use `import meta` anywhere in your ts code

## Context

I am attempting to import a node module (without webpack/babel) that uses `import.meta.url` which caused the original error. However, I found that using `import.meta` anywhere in the electron-react-boilerplate project code also throws the same error. 

In reviewing the `electron-react-boilerplate` babel and webpack configs, it looks like the plugins and settings should support `import.meta`. `.eslintrc.js` is set to `ecmaVersion: 2020` and babel version supports it as well, so I can't see where the issue is. 

Has anyone had success using `import.meta` in their electron-react-boilerplate project? 

## Your Environment

- Node version : 15.4
- electron-react-boilerplate version or branch : 1.4.0
- Operating System and version : OS X 10.14
- Link to your project : private

**Comment by halmos** [comment]
Update: 

Using https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader seems to solve the issue for the use of `import.meta` at the project level, although I'm not sure this is the best approach. 

Additionally, I still haven't been able to solve the issue when `import.meta` is used in a non-transpiled node_module dep.
